version: 1
services:
  - type: web
    name: 69期B組9番のお部屋
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 16
